### ISSUE TITLE
Create Profiles API

### ISSUE THREAD

**Issue by arathivariar** [arathivariar/book-nook-api#1]
## User Story
| Metadata | Description |
| -------- | ----------- |
| Theme | User Profiles  |
| Epic | User Profiles |
| User Story | Create Profiles API |

## Description
As a **developer** I must **create Profiles API** so that I can **perform CRUD operations for user profiles**

## Acceptance Criteria
1. The developer must create Profiles API
2. The developer can perform CRUD operations for user profiles using the API

## Tasks
- [x] Create the Profiles app
- [x] Create the model and serializer
- [x] Perform the migrations
- [x] Create the views and URLs
- [x] Perform CRUD functionalities
