### ISSUE TITLE
Create Comments App

### ISSUE THREAD

**Issue by arathivariar** [arathivariar/book-nook-api#2]
## User Story
| Metadata | Description |
| -------- | ----------- |
| Theme |  Comments, Likes & Followers |
| Epic | Comments, Likes & Followers |
| User Story | Create Comments App |

## Description
As a ** developer ** I want **to create the comments app** so that ** users can add comments**

## Acceptance Criteria
1. The developer must create the Comments app
2. The developer can perform CRUD operations for user comments using the API

## Tasks
- [x] Create the Comments app
- [x] Create the model and serializer
- [x] Perform the migrations
- [x] Create the views and URLs
- [x] Perform CRUD functionalities
