### ISSUE TITLE
Create Likes App

### ISSUE THREAD

**Issue by arathivariar** [arathivariar/book-nook-api#3]
## User Story
| Metadata | Description |
| -------- | ----------- |
| Theme |  Comments, Likes & Followers |
| Epic | Comments, Likes & Followers |
| User Story | Create Likes App |

## Description
As a ** developer ** I want **to create the likes app** so that ** users can like/unlike other user's reviews**

## Acceptance Criteria
1. The developer must create the Likes app
2. The user can like/unlike other user's reviews

## Tasks
- [x] Create the Likes app
- [x] Create the model and serializer
- [x] Perform the migrations
- [x]  Create the views and URLs
- [x] User can like/unlike reviews
