### ISSUE TITLE
Create Followers App

### ISSUE THREAD

**Issue by arathivariar** [arathivariar/book-nook-api#4]
## User Story
| Metadata | Description |
| -------- | ----------- |
| Theme |  Comments, Likes & Followers |
| Epic | Comments, Likes & Followers |
| User Story | Create Followers App |

## Description
As a ** developer ** I want **to create the followers app** so that ** users can follow/unfollow profiles of their preference**

## Acceptance Criteria
1. The developer must create the Followers app
2. The users can follow/unfollow profiles of their preference

## Tasks
- [x] Create the Followers app
- [x] Create the model and serializer
- [x] Perform the migrations
- [x] Create the views and URLs
- [x] Users can follow/unfollow profiles
