### ISSUE TITLE
Filter with like count, comment count and books count

### ISSUE THREAD

**Issue by arathivariar** [arathivariar/book-nook-api#5]
## User Story
| Metadata | Description |
| -------- | ----------- |
| Theme | Data Filtering  |
| Epic | Data Filtering |
| User Story | Filter with like count, comment count, and books count |

## Description
As a **user** I want **to be able to filter with like count, comment count, and books count** so that **I can see more relevant results on my feed**

## Acceptance Criteria
1. The user can filter with like count, comment count, and book count
2. The user can see more relevant results on his/her feed

## Tasks
- [x] Implement the data filtering with like count
- [x]  Implement the data filtering with comment count
- [x]  Implement the data filtering with book count
- [x] Modify the serializer and view with the extra fields
