### ISSUE TITLE
Search book by keywords like book title or author

### ISSUE THREAD

**Issue by arathivariar** [arathivariar/book-nook-api#6]
## User Story
| Metadata | Description |
| -------- | ----------- |
| Theme | Data Filtering  |
| Epic | Data Filtering |
| User Story | Search book by keywords like book title or author |

## Description
As a **user** I want **to search a book by keywords ** so that **I can find a particular book by its title or author**

## Acceptance Criteria
1. The user can search a book with keywords
2. The user can find a particular book by its title or author

## Tasks
- [x] Implement text search feature
- [x] Add book title and author as search fields
- [x] The user can search with keywords
- [x] Appropriate search results are displayed
