### ISSUE TITLE
Heroku Deployment

### ISSUE THREAD

**Issue by arathivariar** [arathivariar/book-nook-api#7]
## User Story
| Metadata | Description |
| -------- | ----------- |
| Theme | Deployment  |
| Epic | Deployment |
| User Story | Heroku Deployment |

## Description
As a **developer** I want **to deploy my project on Heroku** so that **it is available for users**

## Acceptance Criteria
1. Implement the necessary code changes required for deployment
2. Successfully deploy the project on Heroku

## Tasks
- [x] Create a new app in Heroku
- [x] Set the config vars
- [x] Connect the GitHub repo to Heroku
- [x] Add necessary code changes
- [x] Deploy the project
